config/routes.rb
Buddylist::Application.routes.draw do
  get 'blogtags/:tag', to: 'blogpostings#index', as: :blogtag
  get 'filetags/:tag', to: 'filepostings#index', as: :filetag
  get "log_in" => "sessions#new", as: "log_in"
  get "log_out" => "sessions#destroy", as: "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "accept_friendship/:id" => "friendships#accept", as: "accept_friendship"

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  concern :autocompletable do
    get :autocomplete_tag_name, on: :collection
  end

  resources :sessions
  resources :users
  resources :friendships
  resources :personalpostings
  resources :blogpostings, concerns: [:commentable, :autocompletable]
  resources :filepostings, concerns: [:commentable, :autocompletable]
  resources :postings, concerns: [:commentable]

  root :to => 'postings#index'

end

app/models/fileposting.rb
class Fileposting < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy
  include ActiveModel::ForbiddenAttributesProtection
  acts_as_taggable
  mount_uploader :file, FileUploader

  validates_presence_of :user_id, :file, :title

  default_scope :order => 'filepostings.created_at desc'
end

app/controllers/filepostings_controller.rb
class FilepostingsController < ApplicationController
  before_action :set_fileposting, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:show, :index, :edit, :create, :new]
  before_action(only: [:show, :edit, :update]) {set_user(@fileposting) }
  before_action(only: [:show]) {get_comments(@fileposting)}
  before_action(only: [:edit]) {require_own_post(@fileposting)}
  autocomplete :tag, :name, :class_name => 'ActsAsTaggable'

  def index
    if params[:tag]
      @filepostings = Fileposting.tagged_with(params[:tag]).includes(:comments)
    else
      @filepostings = Fileposting.all.includes(:user).includes(:comments)
    end
  end

  def show
  end

  def new
    @fileposting = Fileposting.new
  end

  def edit
  end

  def create
    @fileposting = Fileposting.new(fileposting_params)

    if @fileposting.save
      redirect_to @fileposting, notice: 'Fileposting was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @fileposting.update(fileposting_params)
      redirect_to @fileposting, notice: 'Fileposting was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @fileposting.destroy
    redirect_to filepostings_url, notice: 'Fileposting was successfully destroyed.'
  end

  private
  def set_fileposting
    @fileposting = Fileposting.find(params[:id])
  end

  private
  def fileposting_params()
    params.require(:fileposting).permit(:user_id, :file, :title, :tag_list, :filetype).merge(user_id: current_user.id)
  end
end

app/helpers/fileposting_helper.rb
module FilepostingHelper
end

app/helpers/filepostings_helper.rb
module FilepostingsHelper
end

app/views/filepostings/_fileposting.html.erb
<article class="audiopost span5 well">
  <% if show_username == TRUE %>
      <%= render partial: "users/mini_profile", locals: {posting: fileposting} %>
  <% end %>
  <h4><%= fileposting.title %></h4>
  <% if fileposting.filetype == "Audio" %>
      <audio controls>
        <source src="<%= fileposting.file %>" type="audio/mpeg">
        Your browser does not support the audio element.
      </audio>
  <% else %>
      <video width="320" height="240" controls>
        <source src="<%= fileposting.file %>" type="video/mp4">
        Your browser does not support the video tag.
      </video>
  <% end %>
  <br>

  Posted <%= time_ago_in_words(fileposting.created_at) %> ago

  <strong>Tags:</strong> <%= raw fileposting.tag_list.map { |t| link_to t, filetag_path(t) }.join(', ') %>
  <br>

  <%= link_to 'Show', fileposting, class: 'btn btn-mini btn-primary' %>
  <% if fileposting.comments.count > 0 %>
      <%= fileposting.comments.count %> comment<% if fileposting.comments.count > 1 %>s<% end %>
  <% end %>
</article>

app/views/filepostings/_form.html.erb
<div class="span9">

  <% if @fileposting.errors.any? %>
      <div class="alert alert-error span4">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4>Form is invalid</h4>
        <ul>
          <% for message in @fileposting.errors.full_messages %>
              <li><%= message %></li>
          <% end %>
        </ul>
      </div>
  <% end %>

  <div class="span9">
    <%= form_for @fileposting, html: {multipart: true, class: "form-horizontal"}, class: 'form-horizontal' do |f| %>
        <div class="control-group span6">
          <%= f.label :title, class: 'control-label' %>
          <div class="controls">
            <%= f.text_field :title %>
          </div>
        </div>
        <div class="control-group span6">
          <%= f.label :filetype, class: 'control-label' %>
          <div class="controls">
            <%= f.select :filetype, options_for_select(["Video", "Audio"], @fileposting.filetype)%>
          </div>
        </div>

        <div class="control-group span6">
          <% # Display filename if a file already exists, file is not editable.               %>
          <% if  @fileposting.file? %>
              <%= simple_format "File: " + File.basename(@fileposting.file.path) %>
              <div data-provides="fileupload" class="fileupload fileupload-exists">
                <input type="hidden" value="" name="">

                <div class="input-append">
                  <div class="uneditable-input span3"><i class="icon-file fileupload-exists"></i><span class="fileupload-preview"><%= File.basename(@fileposting.file.path) %></span></div>
                  <span class="btn btn-file"><span class="fileupload-new">Select file</span><span class="fileupload-exists">Change</span><input type="file" name="fileposting[file]" id="fileposting_file"></span><a data-dismiss="fileupload" class="btn fileupload-exists" href="#">Remove</a>
                </div>
              </div>
          <% else %>
              <%= f.label :file, class: 'control-label' %>
              <div class="controls">
                <div class="fileupload fileupload-new" data-provides="fileupload">
                  <div class="input-append"><div class="uneditable-input span3"><i class="icon-file fileupload-exists"></i><span class="fileupload-preview"></span></div>
                    <span class="btn btn-file"><span class="fileupload-new">Select file</span><span class="fileupload-exists">Change</span><%= f.file_field :file %></span><a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
                  </div>
                </div>
              </div>
          <% end %>
        </div>

        <div class="control-group span6">
          <%= f.label :tag_list, "Tags (separated by commas)", class: 'control-label' %>
          <div class="controls">
            <%= f.text_field :tag_list %>
          </div>
        </div>
        <div class="actions span12">
          <%= f.submit 'Create', class: 'btn btn-primary' %>
        </div>
    <% end %>
  </div>
</div>

app/views/filepostings/_tag_fields.html.erb
<div class="control-group">
  <%= b.label :tag_id, "Tag id", class: 'control-label' %>
  <div class="controls">
    <%= b.text_area :tag_id %>
  </div>
</div>
<div class="control-group">
  <%= b.label :tag_id, "fileposting id", class: 'control-label' %>
  <div class="controls">
    <%= b.text_area :fileposting_id %>
  </div>
</div>

app/views/filepostings/edit.html.erb
<h1>Editing fileposting</h1>

<%= render 'form' %>
<div class="span12">
<%= link_to 'Show', @fileposting %> |
<%= link_to 'Back', filepostings_path %>
</div>

app/views/filepostings/index.html.erb
<h1>Filepostings</h1>

<div class="tag_cloud row-fluid span12">
  <% tag_cloud Fileposting.tag_counts, %w[s m l] do |tag, css_class| %>
      <%= link_to tag.name, filetag_path(tag.name), class: css_class %>
  <% end %>
</div>

<%= render partial: "shared/filepostingslist", locals: {show_username: TRUE} %>

app/views/filepostings/new.html.erb
<h1>New fileposting</h1>

<%= render 'form' %>

app/views/filepostings/show.html.erb
<div class="blogpost-detail">
  <div class="span" style="display: none;"></div>
  <h1>Filepost</h1>

  <div class="row-fluid">
    <div class="picture span3"><%= image_tag gravatar(@fileposting.user.email, 60) %></div>
    <header class="span8"><h3><%= link_to @fileposting.user.username, @fileposting.user %></h3></header>
  </div>
  <br>

  <header><h2><%= @fileposting.title %></h2></header>
  <div class="row-fluid">
    <div class="well span5">
      <% if @fileposting.filetype == "Audio" %>
          <audio controls>
            <source src="<%= @fileposting.file %>" type="audio/mpeg">
            Your browser does not support the audio element.
          </audio>
      <% else %>
          <video width="320" height="240" controls>
            <source src="<%= @fileposting.file %>" type="video/mp4">
            Your browser does not support the video tag.
          </video>
      <% end %>
    </div>

    <div class="span5">
      <p><strong>Tags:</strong> <%= raw @fileposting.tag_list.map { |t| link_to t, filetag_path(t) }.join(', ') %></p>

      <p class="muted">Posted <%= time_ago_in_words(@fileposting.created_at) %> ago</p>
    </div>

    <% if current_user == @fileposting.user %>
        <div class="span12">
          <%= link_to 'Edit post', edit_fileposting_path(@fileposting), class: 'btn btn-small btn-info' %>
          <%= link_to 'Delete', @fileposting, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small btn-danger' %>

        </div>
    <% end %>
  </div>

  <%= render partial: "shared/commentlist" %>

  <%= render partial: "shared/newcomment", locals: {posting: @fileposting} %>

  <div class="row-fluid">
    <%= link_to 'Back', filepostings_path, class: 'btn' %>
  </div>
</div>