config/routes.rb
Buddylist::Application.routes.draw do
  get 'blogtags/:tag', to: 'blogpostings#index', as: :blogtag
  get 'filetags/:tag', to: 'filepostings#index', as: :filetag
  get "log_in" => "sessions#new", as: "log_in"
  get "log_out" => "sessions#destroy", as: "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "accept_friendship/:id" => "friendships#accept", as: "accept_friendship"

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  concern :autocompletable do
    get :autocomplete_tag_name, on: :collection
  end

  resources :sessions
  resources :users
  resources :friendships
  resources :personalpostings
  resources :blogpostings, concerns: [:commentable, :autocompletable]
  resources :filepostings, concerns: [:commentable, :autocompletable]
  resources :postings, concerns: [:commentable]

  root :to => 'postings#index'

end

app/models/blogposting.rb
class Blogposting < ActiveRecord::Base
  belongs_to :user
  has_many :comments, :dependent => :destroy
  include ActiveModel::ForbiddenAttributesProtection
  acts_as_taggable

  validates_presence_of :user_id, :content

  default_scope :order => 'blogpostings.created_at desc'
end

app/controllers/blogpostings_controller.rb
class BlogpostingsController < ApplicationController
  before_action :set_blogposting, only: [:show, :edit, :update, :destroy]
  before_action :require_login, only: [:show, :index, :create, :new]
  before_action(only: [:show, :edit, :update]) {set_user(@blogposting) }
  before_action(only: [:show]) {get_comments(@blogposting)}
  before_action(only: [:edit]) {require_own_post(@blogposting)}
  autocomplete :tag, :name, :class_name => 'ActsAsTaggable'

  def index
    if params[:tag]
      @blogpostings = Blogposting.tagged_with(params[:tag]).includes(:comments)
    else
      @blogpostings = Blogposting.all.includes(:user).includes(:comments)
    end
  end

  def show
    @comments = @blogposting.comments.all
  end

  def new
    @blogposting = Blogposting.new
  end

  def edit

  end

  def create

    @blogposting = Blogposting.new(user_id: current_user.id, content: blogposting_params['content'], tag_list: blogposting_params['tag_list'])
    respond_to do |format|
      if @blogposting.save
        format.html { redirect_to @blogposting, notice: 'Blogposting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @blogposting }
      else
        format.html { render action: 'new' }
        format.json { render json: @blogposting.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blogposting.update(blogposting_params)
        format.html { redirect_to @blogposting, notice: 'Blogposting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @blogposting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blogposting.destroy
    respond_to do |format|
      format.html { redirect_to blogpostings_url }
      format.json { head :no_content }
    end
  end

  private
  def set_blogposting
    @blogposting = Blogposting.find(params[:id])
  end

  private
  def blogposting_params
    params.require(:blogposting).permit(:user_id, :content, :tag_list)
  end

end

app/helpers/blogpostings_helper.rb
module BlogpostingsHelper
end

app/views/blogpostings/_blogposting.html.erb
<article class="blogpost span5 well">
  <% if show_username == TRUE %>
      <%= render partial: "users/mini_profile", locals: {posting: blogposting} %>
  <% end %>
  <%= simple_format truncate(blogposting.content, :length => 200, :separator => ' ') %>

  <p class="muted">Posted <%= time_ago_in_words(blogposting.created_at) %> ago

    <strong>Tags:</strong> <%= raw blogposting.tag_list.map { |t| link_to t, blogtag_path(t) }.join(', ') %></p>

  <%= link_to 'Show post', blogposting, class: 'btn btn-mini btn-primary' %>
  <% if blogposting.comments.count > 0 %>
      <%= blogposting.comments.count %> comment<% if blogposting.comments.count > 1 %>s<% end %>
  <% end %>
</article>

app/views/blogpostings/_form.html.erb
<% if @blogposting.errors.any? %>
    <div class="alert alert-error span4">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @blogposting.errors.full_messages %>
            <li><%= message %></li>
        <% end %>
      </ul>
    </div>
<% end %>

<%= form_for([@blogposting]) do |f| %>
    <div class="field">
      <%= f.label :content %>
      <br>
      <%= f.text_area :content %>
    </div>

    <div class="field">
      <%= f.label :tag_list, "Tags (separated by commas)" %>
      <br/>
      <%= f.text_field :tag_list %>
    </div>

    <div class="actions">
      <%= f.submit "Create blogposting", class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/blogpostings/_tag_fields.html.erb
<div class="field">
  <%= b.label :tag_id, "Tag id" %>
  <br>
  <%= b.text_area :tag_id %>
</div>
<div class="field">
  <%= b.label :tag_id, "Blogposting id" %>
  <br>
  <%= b.text_area :blogposting_id %>
</div>

app/views/blogpostings/edit.html.erb
<h1>Editing blogposting</h1>

<%= render 'form' %>

<%= link_to 'Show', @blogposting %> |
<%= link_to 'Back', blogpostings_path %>

app/views/blogpostings/index.html.erb
<h1>Blogpostings</h1>

<div class="tag_cloud row-fluid span12">
  <% tag_cloud Blogposting.tag_counts, %w[s m l] do |tag, css_class| %>
      <%= link_to tag.name, blogtag_path(tag.name), class: css_class %>
  <% end %>
</div>

<%= render partial: "shared/blogpostingslist", locals: {show_username: TRUE} %>

app/views/blogpostings/new.html.erb
<h1>New blogposting</h1>

<%= render 'form' %>

app/views/blogpostings/show.html.erb
<div class="blogpost-detail">
  <div class="span" style="display: none;"></div>
  <h1>Blogpost</h1>

  <div class="row-fluid">
    <div class="picture span3"><%= image_tag gravatar(@blogposting.user.email, 60) %></div>
    <header class="span8"><h3><%= link_to @blogposting.user.username, @blogposting.user %></h3></header>
  </div>
  <br>

  <div class="row-fluid">
    <div class="well span5">
      <%= simple_format @blogposting.content %>
    </div>

    <div class="span5">
      <p><strong>Tags:</strong> <%= raw @blogposting.tag_list.map { |t| link_to t, blogtag_path(t) }.join(', ') %></p>

      <p class="muted">Posted <%= time_ago_in_words(@blogposting.created_at) %> ago</p>
    </div>

    <% if current_user == @blogposting.user %>
        <div class="span12">
          <%= link_to 'Edit post', edit_blogposting_path(@blogposting), class: 'btn btn-small btn-info' %>
          <%= link_to 'Delete', @blogposting, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small btn-danger' %>
        </div>
    <% end %>
  </div>

  <%= render partial: "shared/commentlist" %>

  <%= render partial: "shared/newcomment", locals: {posting: @blogposting} %>

  <div class="row-fluid">
    <%= link_to 'Back', blogpostings_path, class: 'btn' %>
  </div>
</div>