config/routes.rb
Buddylist::Application.routes.draw do
  get 'blogtags/:tag', to: 'blogpostings#index', as: :blogtag
  get 'filetags/:tag', to: 'filepostings#index', as: :filetag
  get "log_in" => "sessions#new", as: "log_in"
  get "log_out" => "sessions#destroy", as: "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  get "accept_friendship/:id" => "friendships#accept", as: "accept_friendship"

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  concern :autocompletable do
    get :autocomplete_tag_name, on: :collection
  end

  resources :sessions
  resources :users
  resources :friendships
  resources :personalpostings
  resources :blogpostings, concerns: [:commentable, :autocompletable]
  resources :filepostings, concerns: [:commentable, :autocompletable]
  resources :postings, concerns: [:commentable]

  root :to => 'postings#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Buddylist</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Buddylist">
  <meta name="author" content="Maarten Kuiper">
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "bootstrap/bootstrap", media: "all", "data-turbolinks-track" => true %>
  <!-- Le styles -->
  <%= stylesheet_link_tag "application", "data-turbolinks-track" => true %>

  <style>
      body {
          padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
  </style>
  <%= stylesheet_link_tag "bootstrap/bootstrap-responsive", media: "all", "data-turbolinks-track" => true %>

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="../assets/js/html5shiv.js"></script>
  <![endif]-->

  <!-- Fav and touch icons -->
  <%= favicon_link_tag 'favicon.png' %>
</head>

<body>

<nav class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Buddylist", root_url, class: "brand" %>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              List
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Users", users_url %></li>
              <li><%= link_to "Blogpostings", blogpostings_url %></li>
              <li><%= link_to "Filepostings", filepostings_url %></li>
            </ul>
          </li>
        </ul>
        <% if current_user %>
            <ul class="nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  New
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Blogposting', new_blogposting_path %></li>
                  <li><%= link_to "Fileposting", new_fileposting_path %></li>

                </ul>
              </li>
            </ul>
        <% end %>
        <ul class="nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <% if current_user %>
                  <%= current_user.username %> <%if current_user.requested_friendships.count > 0 %>(<%= current_user.requested_friendships.count %>)<% end %>
              <% else %>
                  Account
              <% end %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user %>
                  <li><%= link_to "My profile", current_user %></li>
                  <% if current_user.requested_friendships.count > 0 %>
                      <li><%= link_to 'Requested friendships', friendships_url %></li>
                  <% end %>
                  <li><%= link_to "Log out", log_out_path %></li>
              <% else %>
                  <li><%= link_to "Log in", log_in_path %></li>
                  <li><%= link_to "Sign up", sign_up_path %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

<% flash.each do |name, msg| %>
    <div class="page-alert">
      <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      </div>
    </div>
<% end %>

<div class="container">
  <div class="row-fluid span12">

    <%= yield %>

  </div>
</div>
<!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
<script>
    $('a.dropdown-toggle, .dropdown-menu a').on('touchstart', function (e) {
        e.stopPropagation();
    });
</script>

</body>
</html>